### PR TITLE
Fixed the query structure of the tables to scan rows from snowflake DB Closes #77

### LINKED ISSUE #77: Getting error while fetching most of the tables
**Describe the bug**
Getting error while querying tables, I attaching all the tables and the respective error I am getting while querying, I am using Postgres 15 FDW

**Steampipe version (`steampipe -v`)**
Using postgres15 FDW

**Plugin version (`steampipe plugin list`)**
Example: v0.8.0

snowflake_schemata   -   
	ERROR:  snowflake: rpc error: code = Internal desc = hydrate function listSnowflakeSchemata failed with panic unknown column OWNER_ROLE_TYPE

snowflake_view_grant  -   
 	ERROR:  snowflake: rpc error: code = Internal desc = 'List' call for table 'snowflake_view_grant' is missing 3 required quals:
    column:'view_name' operator: =
    column:'database_name' operator: =
    column:'schema_name' operator: =

snowflake_session    -
	ERROR:  snowflake: rpc error: code = Internal desc = hydrate function listSnowflakeSession failed with panic unknown column CLOSED_REASON

snowflake_user       -
	ERROR:  snowflake: sql: expected 28 destination arguments in Scan, not 26
	
snowflake_view     -
	ERROR:  snowflake: sql: expected 12 destination arguments in Scan, not 10

snowflake_database_grant     -
	ERROR:  snowflake: rpc error: code = Internal desc = 'List' call for table 'snowflake_database_grant' is missing 1 required qual: column:'database' operator: =

snowflake_user_grant		-
	ERROR:  snowflake: rpc error: code = Internal desc = 'List' call for table 'snowflake_user_grant' is missing 1 required qual: column:'username' operator: =

snowflake_role_grant		-
	ERROR:  snowflake: rpc error: code = Internal desc = 'List' call for table 'snowflake_role_grant' is missing 1 required qual: column:'role' operator: =

snowflake_warehouse         -
	ERROR:  snowflake: missing destination name budget in *[]snowflake.Warehouse

snowflake_account_grant		-
	ERROR:  snowflake: sql: expected 9 destination arguments in Scan, not 8

snowflake_database          -
	ERROR:  snowflake: sql: expected 12 destination arguments in Scan, not 9

snowflake_login_history		-
	ERROR:  snowflake: rpc error: code = Internal desc = hydrate function listSnowflakeLoginHistory failed with panic unknown column CONNECTION

snowflake_network_policy	-
	ERROR:  snowflake: sql: expected 7 destination arguments in Scan, not 5

### PR DESCRIPTION
**Pull request by ParthaI**
# Example query results

<details>
  <summary>Results</summary>

```
> select * from snowflake_user_grant where username = 'PARTHA'
+----------+--------------+---------------------------+------------+------------+----------------+---------+--------------------+----------------------------------------------------------------------+----------------------------------------------------------------------+
| username | role         | created_on                | granted_to | granted_by | region         | account | sp_connection_name | sp_ctx                                                               | _ctx                                                                 |
+----------+--------------+---------------------------+------------+------------+----------------+---------+--------------------+----------------------------------------------------------------------+----------------------------------------------------------------------+
| PARTHA   | ACCOUNTADMIN | 2024-09-04T20:12:21+05:30 | USER       |            | ap-southeast-1 | en54885 | snowflake          | {"connection_name":"snowflake","steampipe":{"sdk_version":"5.10.1"}} | {"connection_name":"snowflake","steampipe":{"sdk_version":"5.10.1"}} |
| PARTHA   | ORGADMIN     | 2024-09-04T20:12:26+05:30 | USER       |            | ap-southeast-1 | en54885 | snowflake          | {"connection_name":"snowflake","steampipe":{"sdk_version":"5.10.1"}} | {"connection_name":"snowflake","steampipe":{"sdk_version":"5.10.1"}} |
+----------+--------------+---------------------------+------------+------------+----------------+---------+--------------------+----------------------------------------------------------------------+----------------------------------------------------------------------+

> select * from snowflake_session
+-------------+-----------+---------------------------+-----------------------+-----------------------+----------------------------+-----------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------->
| session_id  | user_name | created_on                | authentication_method | client_application_id | client_application_version | client_build_id | client_environment                                                                                                                                                 >
+-------------+-----------+---------------------------+-----------------------+-----------------------+----------------------------+-----------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------->
| 43424309273 | PARTHA    | 2024-09-05T10:07:18+05:30 | Password              | Go 1.10.1             | 1.10.1                     |                 | {"APPLICATION":"Go","GO_VERSION":"go1.21.4","OCSP_MODE":"FAIL_OPEN","OS":"darwin","OS_VERSION":"gc-arm64"}                                                         >
| 43424296889 | PARTHA    | 2024-09-05T09:50:06+05:30 | OAuth                 | Go 1.1.5              | 1.1.5                      |                 | {"APPLICATION":"Snowflake Web App"}                                                                                                                                >
| 43424302809 | PARTHA    | 2024-09-05T09:50:05+05:30 | OAuth                 | Go 1.1.5              | 1.1.5                      |                 | {"APPLICATION":"Snowflake Web App"}                                                                                                                                >
| 43424306325 | PARTHA    | 2024-09-05T09:36:36+05:30 | Password              | Go 1.10.1             | 1.10.1                     |                 | {"APPLICATION":"Go","GO_VERSION":"go1.21.4","OCSP_MODE":"FAIL_OPEN","OS":"darwin","OS_VERSION":"gc-arm64"}                                                         >
| 43424306329 | PARTHA    | 2024-09-05T09:50:06+05:30 | OAuth                 | Go 1.1.5              | 1.1.5                      |                 | {"APPLICATION":"Snowflake Web App"}                                                                                                                                >
| 43424302845 | PARTHA    | 2024-09-05T10:34:11+05:30 | Password              | Go 1.10.1             | 1.10.1                     |                 | {"APPLICATION":"Go","GO_VERSION":"go1.21.4","OCSP_MODE":"FAIL_OPEN","OS":"darwin","OS_VERSION":"gc-arm64"}                                                         >
| 43424297145 | PARTHA    | 2024-09-04T20:59:57+05:30 | OAuth                 | Snowflake UI 1.1.5    | 1.1.5                      | 0               | {"APPLICATION":"Snowflake Web App (Search)"}                                                                                                                       >

> select * from snowflake_schemata
+-----------+--------------------------+------------+--------------+--------------+----------------+--------------+-------------------+---------+---------------------------+---------------------------+---------------------------+----------------+---------+--------------------+------------------------------------->
| schema_id | schema_name              | catalog_id | catalog_name | schema_owner | retention_time | is_transient | is_managed_access | comment | created                   | last_altered              | deleted                   | region         | account | sp_connection_name | sp_ctx                              >
+-----------+--------------------------+------------+--------------+--------------+----------------+--------------+-------------------+---------+---------------------------+---------------------------+---------------------------+----------------+---------+--------------------+------------------------------------->
| 4         | ORGANIZATION_USAGE_LOCAL | 1          | SNOWFLAKE    | SNOWFLAKE    | 1              | NO           | NO                | <null>  | 2024-09-04T20:41:19+05:30 | 2024-09-04T20:42:26+05:30 | 2024-09-04T20:42:26+05:30 | ap-southeast-1 | en54885 | snowflake          | {"connection_name":"snowflake","stea>
| 7         | TRUST_CENTER             | 1          | SNOWFLAKE    | SNOWFLAKE    | 1              | NO           | NO                | <null>  | 2024-09-04T20:42:30+05:30 | 2024-09-04T20:42:30+05:30 | <null>                    | ap-southeast-1 | en54885 | snowflake          | {"connection_name":"snowflake","stea>
| 2         | LOCAL                    | 1          | SNOWFLAKE    | SNOWFLAKE    | 1              | NO           | NO                | <null>  | 2024-09-04T20:41:08+05:30 | 2024-09-04T20:41:08+05:30 | <null>                    | ap-southeast-1 | en54885 | snowflake          | {"connection_name":"snowflake","stea>
| 13        | SECURITY_ESSENTIALS      | 1          | SNOWFLAKE    | SNOWFLAKE    | 1              | NO           | NO                | <null>  | 2024-09-04T20:43:08+05:30 | 2024-09-04T20:43:08+05:30 | <null>                    | ap-southeast-1 | en54885 | snowflake          | {"connection_name":"snowflake","stea>
| 5         | TELEMETRY                | 1          | SNOWFLAKE    | SNOWFLAKE    | 1              | NO           | NO                | <null>  | 2024-09-04T20:42:28+05:30 | 2024-09-04T20:42:28+05:30 | <null>                    | ap-southeast-1 | en54885 | snowflake          | {"connection_name":"snowflake","stea>
| 9         | CIS_COMMON               | 1          | SNOWFLAKE    | SNOWFLAKE    | 1              | NO           | NO                | <null>  | 2024-09-04T20:42:52+05:30 | 2024-09-04T20:42:52+05:30 | <null>                    | ap-southeast-1 | en54885 | snowflake          | {"connection_name":"snowflake","stea>

> select * from snowflake_role
+---------------+---------------------------+-------------------+-----------------------------------------------------------------------------------+---------------+------------------+------------+------------+--------------+-------+----------------+---------+--------------------+--------------------------------->
| name          | created_on                | assigned_to_users | comment                                                                           | granted_roles | granted_to_roles | is_current | is_default | is_inherited | owner | region         | account | sp_connection_name | sp_ctx                          >
+---------------+---------------------------+-------------------+-----------------------------------------------------------------------------------+---------------+------------------+------------+------------+--------------+-------+----------------+---------+--------------------+--------------------------------->
| SYSADMIN      | 2024-09-04T20:12:21+05:30 | 0                 | System administrator can create and manage databases and warehouses.              | 0             | 1                | N          | N          | Y            |       | ap-southeast-1 | en54885 | snowflake          | {"connection_name":"snowflake",">
| ORGADMIN      | 2024-09-04T20:12:22+05:30 | 1                 | Organization administrator can manage organizations and accounts in organizations | 0             | 0                | N          | N          | N            |       | ap-southeast-1 | en54885 | snowflake          | {"connection_name":"snowflake",">
| PUBLIC        | 2024-09-04T20:12:21+05:30 | 0                 | Public role is automatically available to every user in the account.              | 0             | 0                | N          | N          | Y            |       | ap-southeast-1 | en54885 | snowflake          | {"connection_name":"snowflake",">
| USERADMIN     | 2024-09-04T20:12:21+05:30 | 0                 | User administrator can create and manage users and roles                          | 0             | 1                | N          | N          | Y            |       | ap-southeast-1 | en54885 | snowflake          | {"connection_name":"snowflake",">
| ACCOUNTADMIN  | 2024-09-04T20:12:21+05:30 | 1                 | Account administrator can manage all aspects of the account.                      | 2             | 0                | Y          | Y          | N            |       | ap-southeast-1 | en54885 | snowflake          | {"connection_name":"snowflake",">
| SECURITYADMIN | 2024-09-04T20:12:21+05:30 | 0                 | Security administrator can manage security aspects of the account.                | 1             | 1                | N          | N          | Y            |       | ap-southeast-1 | en54885 | snowflake          | {"connection_name":"snowflake",">
+---------------+---------------------------+-------------------+-----------------------------------------------------------------------------------+---------------+------------------+------------+------------+--------------+-------+----------------+---------+--------------------+--------------------------------->

> select * from snowflake_role_grant where role = 'ACCOUNTADMIN'
+--------------+---------------------------+------------+--------------+------------+----------------+---------+--------------------+----------------------------------------------------------------------+----------------------------------------------------------------------+
| role         | created_on                | granted_to | grantee_name | granted_by | region         | account | sp_connection_name | sp_ctx                                                               | _ctx                                                                 |
+--------------+---------------------------+------------+--------------+------------+----------------+---------+--------------------+----------------------------------------------------------------------+----------------------------------------------------------------------+
| ACCOUNTADMIN | 2024-09-04T20:12:21+05:30 | USER       | PARTHA       |            | ap-southeast-1 | en54885 | snowflake          | {"connection_name":"snowflake","steampipe":{"sdk_version":"5.10.1"}} | {"connection_name":"snowflake","steampipe":{"sdk_version":"5.10.1"}} |
+--------------+---------------------------+------------+--------------+------------+----------------+---------+--------------------+----------------------------------------------------------------------+------------------------------------------------------------------

> select * from snowflake_login_history
+-------------+---------------------------+------------+-----------+----------------+----------------------+-------------------------+-----------------------------+------------------------------+------------+------------+---------------+------------------+----------------+---------+--------------------+---------->
| event_id    | event_timestamp           | event_type | user_name | client_ip      | reported_client_type | reported_client_version | first_authentication_factor | second_authentication_factor | is_success | error_code | error_message | related_event_id | region         | account | sp_connection_name | sp_ctx   >
+-------------+---------------------------+------------+-----------+----------------+----------------------+-------------------------+-----------------------------+------------------------------+------------+------------+---------------+------------------+----------------+---------+--------------------+---------->
| 43424286265 | 2024-09-05T10:51:26+05:30 | LOGIN      | PARTHA    | 122.164.86.26  | OTHER                | 1.10.1                  | PASSWORD                    | <null>                       | YES        | <null>     | <null>        | 0                | ap-southeast-1 | en54885 | snowflake          | {"connect>
| 43424286269 | 2024-09-05T11:21:22+05:30 | LOGIN      | PARTHA    | 122.164.86.26  | OTHER                | 1.10.1                  | PASSWORD                    | <null>                       | YES        | <null>     | <null>        | 0                | ap-southeast-1 | en54885 | snowflake          | {"connect>

> select * from snowflake_database
+-----------------------+---------------------------+-----------------------------------------------------------------------+------------+------------+---------+---------------------------------------------------------+--------------+----------------+----------------+---------+--------------------+--------------->
| name                  | created_on                | comment                                                               | is_current | is_default | options | origin                                                  | owner        | retention_time | region         | account | sp_connection_name | sp_ctx        >
+-----------------------+---------------------------+-----------------------------------------------------------------------+------------+------------+---------+---------------------------------------------------------+--------------+----------------+----------------+---------+--------------------+--------------->
| SNOWFLAKE             | 2024-09-04T20:12:22+05:30 |                                                                       | N          | N          |         | SNOWFLAKE.ACCOUNT_USAGE                                 |              | 0              | ap-southeast-1 | en54885 | snowflake          | {"connection_n>
| SNOWFLAKE_SAMPLE_DATA | 2024-09-04T20:12:26+05:30 | Preloaded TPCH Data provided by Snowflake during account provisioning | N          | N          |         | SFSALESSHARED.SFC_SAMPLES_AWSAPSOUTHEAST1SG.SAMPLE_DATA | ACCOUNTADMIN | 0              | ap-southeast-1 | en54885 | snowflake          | {"connection_n>
+-----------------------+---------------------------+-----------------------------------------------------------------------+------------+------------+---------+---------------------------------------------------------+--------------+----------------+----------------+---------+--------------------+--------------->

> select * from snowflake_account_parameter
+--------------------------------------------------------------+----------------------------------+----------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------>
| key                                                          | value                            | default                          | description                                                                                                                                                                        >
+--------------------------------------------------------------+----------------------------------+----------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------>
| ABORT_DETACHED_QUERY                                         | false                            | false                            | If true, Snowflake will automatically abort queries when it detects that the client has disappeared.                                                                               >
| BINARY_OUTPUT_FORMAT                                         | HEX                              | HEX                              | display format for binary                                                                                                                                                          >
| AUTOCOMMIT_API_SUPPORTED                                     | true                             | true                             | Whether autocommit feature is enabled for this client. This parameter is for                                                                                                       >

```

</details>

### CODE REVIEW

File: snowflake/table_snowflake_warehouse.go [hunk 1]
```diff
@@ -77,6 +77,8 @@ type Warehouse struct {
 	Suspended       sql.NullInt64  `json:"suspended" db:"suspended"`
 	UUID            sql.NullString `json:"uuid" db:"uuid"`
 	ScalingPolicy   sql.NullString `json:"scaling_policy" db:"scaling_policy"`
+	Budget          sql.NullString `json:"budget" db:"budget"`
+	OwnerRoleType          sql.NullString `json:"owner_role_type" db:"owner_role_type"`
```
Comment (misraved) [inline snowflake/table_snowflake_warehouse.go:81]: @ParthaI could you please fix the indentation over here?

File: snowflake/table_snowflake_view_grant.go [hunk 2]
```diff
@@ -31,7 +31,7 @@ func tableSnowflakeViewGrant(_ context.Context) *plugin.Table {
 			{Name: "schema_name", Type: proto.ColumnType_STRING, Transform: transform.FromQual("schema_name"), Description: "The name of the schema in which the view exists."},
 			{Name: "privilege", Type: proto.ColumnType_STRING, Description: "A defined level of access to an object."},
 			{Name: "created_on", Type: proto.ColumnType_TIMESTAMP, Description: "Date and time privilege was granted."},
-			{Name: "grant_option", Type: proto.ColumnType_BOOL, Description: "If set to TRUE, the recipient role can grant the privilege to other roles."},
+			{Name: "grant_option", Type: proto.ColumnType_STRING, Description: "If set to TRUE, the recipient role can grant the privilege to other roles."},
```
Comment (misraved) [inline snowflake/table_snowflake_view_grant.go:34]: The value suggests that it is a boolean column. Should we raise an issue in the SDK?

File: snowflake/table_snowflake_user.go [hunk 3]
```diff
@@ -88,6 +88,8 @@ type User struct {
 	LockedUntilTime       sql.NullTime   `json:"locked_until_time"`
 	HasPassword           sql.NullString `json:"has_password"`
 	HasRsaPublicKey       sql.NullString `json:"has_rsa_public_key"`
+	Type                  sql.NullString `json:"type"`
+	HasMFA                sql.NullBool  `json:"has_mfa"`
```
Comment (misraved) [inline snowflake/table_snowflake_user.go:92]: @ParthaI could you please fix the indentation over here?

**Review by misraved — COMMENTED** [review]
Please take a look at the review comments.

@ParthaI the title of the PR does not coincide with the fixes made in the PR. Should the title be updated?

**Review by misraved — APPROVED** [review]
